project:
  type: book
  output-dir: docs
  preview:
    port: 4200
    watch-inputs: true

book:
  title: "Människovetaren och statistiken"
  author: "Oliver Saal"
  language: "sv-FI"
  references: "references.bib"
  
  chapters:
    - "index.qmd"
    - part: "Analysens logik"
      chapters:
        - "vad-är-statistik.qmd"
        - "vad-är-data.qmd"
        - "från-ide-till-rapport.qmd"
        - "variabler.qmd"
        - "modeller.qmd"
        - "statistisk-inferens.qmd"
    - part: "R-miljön"
      chapters:
        - "introduktion-till-r-miljön.qmd"
        - "grundläggande-kunskaper-i-programmering.qmd"
        - "r-del-två.qmd"
        - "grafik.qmd"
    - part: "Statistiska metoder"
      chapters:
        - "univariat-analys.qmd"
        - "bivariat-analys.qmd"
    - "källförteckning.qmd"
        
  description: '"Människovetaren och statistiken" är en grundkurs i den statistiska analysens process, ämnad för universitetsstuderande i samhälls- och humanvetenskaper. Målet är att göra statistisk analys tillgänglig och begriplig, och att minska studentens statistikångest genom att synliggöra hur statistik egentligen är likt all annan forskning, fastän med siffror. Boken är en work-in-progress, med början den 12:e februari 2023.'
format:
  html:
    theme: cosmo
    css: "style.css"
    citation-location: margin
    reference-location: margin