<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="“Människovetaren och statistiken” är en grundkurs i den statistiska analysens process, ämnad för universitetsstuderande i samhälls- och humanvetenskaper. Målet är att göra statistisk analys tillgänglig och begriplig, och att minska studentens statistikångest genom att synliggöra hur statistik egentligen är likt all annan forskning, fastän med siffror. Boken är en work-in-progress, med början den 12:e februari 2023.">

<title>Människovetaren och statistiken - 12&nbsp; Bivariat analys</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./källförteckning.html" rel="next">
<link href="./univariat-analys.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bivariat analys</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Människovetaren och statistiken</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Förord</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Analysens logik</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vad-är-statistik.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Vad är statistik?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vad-är-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Vad är data?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./från-ide-till-rapport.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Från idé till rapport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./variabler.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variabler</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modeller.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modeller</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistisk-inferens.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistisk inferens</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">R-miljön</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduktion-till-r-miljön.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduktion till R-miljön</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./grundläggande-kunskaper-i-programmering.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Grundläggande kunskaper i R-programmering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-del-två.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">R, del två</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./grafik.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Grafik</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Statistiska metoder</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./univariat-analys.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Univariat analys</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariat-analys.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bivariat analys</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./källförteckning.html" class="sidebar-item-text sidebar-link">Källförteckning</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#korstabulering" id="toc-korstabulering" class="nav-link active" data-scroll-target="#korstabulering"><span class="toc-section-number">12.1</span>  Korstabulering</a>
  <ul class="collapse">
  <li><a href="#chi-kvadrat-testet-chi2" id="toc-chi-kvadrat-testet-chi2" class="nav-link" data-scroll-target="#chi-kvadrat-testet-chi2"><span class="toc-section-number">12.1.1</span>  Chi-kvadrat-testet: <span class="math inline">\(\chi^2\)</span></a></li>
  </ul></li>
  <li><a href="#students-t-test" id="toc-students-t-test" class="nav-link" data-scroll-target="#students-t-test"><span class="toc-section-number">12.2</span>  Students T-test</a>
  <ul class="collapse">
  <li><a href="#t-test-för-enkla-urval" id="toc-t-test-för-enkla-urval" class="nav-link" data-scroll-target="#t-test-för-enkla-urval"><span class="toc-section-number">12.2.1</span>  T-test för enkla urval</a></li>
  <li><a href="#t-test-för-dubbla-urval" id="toc-t-test-för-dubbla-urval" class="nav-link" data-scroll-target="#t-test-för-dubbla-urval"><span class="toc-section-number">12.2.2</span>  T-test för dubbla urval</a></li>
  <li><a href="#rapportering-av-t-test" id="toc-rapportering-av-t-test" class="nav-link" data-scroll-target="#rapportering-av-t-test"><span class="toc-section-number">12.2.3</span>  Rapportering av t-test</a></li>
  </ul></li>
  <li><a href="#likhetstest-och-minimistorlekstest" id="toc-likhetstest-och-minimistorlekstest" class="nav-link" data-scroll-target="#likhetstest-och-minimistorlekstest"><span class="toc-section-number">12.3</span>  Likhetstest och minimistorlekstest</a></li>
  <li><a href="#korrelationsanalys" id="toc-korrelationsanalys" class="nav-link" data-scroll-target="#korrelationsanalys"><span class="toc-section-number">12.4</span>  Korrelationsanalys</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bivariat analys</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="packages-info">
<div class="left-adj">
<p><strong>Du behöver följande paket:</strong></p>
</div>
<p><code>stats</code>: R:s inbyggda statistikpaket.</p>
<p><code>gmodels</code>: Paket för generella lineära modeller.</p>
<p><code>DescTools</code>: Paket för deskriptiva mått och bivariat analys.</p>
<p><code>ggplot2</code>: Paket för att generera grafik.</p>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'DescTools':
  method         from 
  reorder.factor gdata</code></pre>
</div>
</div>
<p>Detta kapitel handlar om de första sambandsanalyserna du kommer att göra: bivariata analyser, med en beroende variabel och en oberoende variabel. Analysmetoderna är uppdelade enligt skalenivåer. Först kommer korstabuleringen, som kan utföras på två nominalvariabler. Sedan är det dags för ordningstesten, vilka fungerar på ordinalskalenivå. Efter det inleder vi variansanalysen med enkel ANOVA, vilken har en beroende variabel på intervall- eller kvotskala och en oberoende variabel på nominal- eller ordinalskala. T-testet är ett likadant, men något enklare, test som likväl utförs på kvantitativa beroende variabler, men med en binär oberoende variabel. Till sist introduceras korrelationsanalysen, som kräver intervall- eller kvotvariabler i bägge position.</p>
<section id="korstabulering" class="level2 page-columns page-full" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="korstabulering"><span class="header-section-number">12.1</span> Korstabulering</h2>
<p>Du har tidigare blivit bekant med frekvenstabeller i denna bok. En frekvenstabell, för att påminna, är en tabell som innehåller information på hur många analysobjekt har fått ett visst värde på variabeln i fråga. Frekvenstabeller är därmed univariata metoder, eftersom de presenterar information på en variabel.</p>
<div class="page-columns page-full"><p><strong>Korstabellen</strong> (eng. <em>crosstabulation</em> eller förkortat <em>crosstab</em>) är en bivariat version av detta. Istället för att lägga variabelnivåerna i raderna och frekvensen i kolumnerna, lägger vi den beroende variabeln i raderna och den oberoende variabeln i kolumnerna<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;Egentligen är ordningen arbiträr, du kan likväl ha beroende i kolumnerna och oberoende i raderna. Av konvention brukar man följa ordningen jag nämner, men gör hur du vill - så länge du säger tydligt vad du menar.</p></li></div></div>
<p>Idén med korstabellen är att vi kan granska enskilda frekvenser för vissa kategorier, och därmed se eventuella skillnader i beroende variabelns grad enligt oberoende variabel. Ser vi skillnader så tyder det på att det finns ett förhållande mellan beroende och oberoende variablerna. Om vi inte ser någon skillnad, så finns det troligen inte ett förhållande (men glöm inte elaborering!).</p>
<p>I R kan du utföra en korstabulering med funktionen <code>stats::xtabs(formula, data)</code>. Funktionen tar två obligatoriska argument: <code>formula</code> beskriver vad som ska korstabuleras, och <code>data</code> beskriver varifrån data ska hämtas. Funktionen returnerar en korstabell:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>korstabell <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span>alcgp <span class="sc">+</span> tobgp, <span class="at">data =</span> esoph)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>korstabell</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           tobgp
alcgp       0-9g/day 10-19 20-29 30+
  0-39g/day        6     6     5   6
  40-79            6     6     6   5
  80-119           6     6     4   5
  120+             6     6     5   4</code></pre>
</div>
</div>
<p>[BYT TILL BÄTTRE EXEMPEL]</p>
<p>Vi kan se en tabell med två variabler: <code>alcgp</code> i raderna, vilket står för gram av alkohol per dag, och <code>tobgp</code>, vilket står för gram av tobak per dag. Om vi granskar cellerna så tycks det inte finnas ett förhållande mellan alkoholkonsumption och tobakskonsumption i vårt data: alla celler har ungefär lika stora värden i sig.</p>
<section id="chi-kvadrat-testet-chi2" class="level3 page-columns page-full" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="chi-kvadrat-testet-chi2"><span class="header-section-number">12.1.1</span> Chi-kvadrat-testet: <span class="math inline">\(\chi^2\)</span></h3>
<div class="page-columns page-full"><p>Chi<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>-kvadrat-testet är ett osäkerhetstest för korstabeller. Vi kan använda chi-kvadrat-testet för att undersöka huruvida våra observerade cellvärden (vårt data) motsvarar vad vi skulle förvänta oss under nollhypotesen. I detta fall är nollhypotesen att det inte finns ett förhållande mellan de två variablerna i korstabellen.</p><div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;Uttalas [<span class="math inline">\(k^h\)</span>i:], med hårt K-ljud</p></li></div></div>
<p><span class="math inline">\(\chi^2\)</span>-testet kan förstås som en generell lineär modell (GLM). Detta betyder att den gör samma sak som alla andra modeller: <span class="math inline">\(\text{Utsaga} = \text{Modell} + \text{Felvärde}\)</span>. <em>De facto</em> räknar <span class="math inline">\(\chi^2\)</span> faktiskt avvikelsens kvadratsumma (se kapitel XXX), men med en liten modifikation:</p>
<p><span class="math display">\[\chi^2 = \sum_{i=1}^{n}\frac{(\text{observerat}_i-\text{modell}_i)^2}{\text{modell}_i} \]</span> I människospråk: <span class="math inline">\(\chi^2\)</span> räknar kvadratskillnaden mellan det observerade cellvärdet och det förväntande cellvärdet, och dividerar detta med det förväntade cellvärdet. Sedan räknar den summan av alla dessa beräkningar för varje cellvärde. Slutresultatet är ett värde, <span class="math inline">\(\chi^2\)</span>, som återspeglas i en <span class="math inline">\(\chi^2\)</span>-fördelning:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="bivariat-analys_files/figure-html/chi-sq-dist-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hur räknas dessa skillnader? <span class="math inline">\(\chi^2\)</span> inleder med att räkna en modell för varje kombination av beroende och oberoende variablernas kategorier i korstabellen. Om vi t.ex. har två binära variabler, så summerar <span class="math inline">\(\chi^2\)</span> följande modeller: <span class="math inline">\(\text{modell}_{00}\)</span>, <span class="math inline">\(\text{modell}_{01}\)</span>, <span class="math inline">\(\text{modell}_{10}\)</span> och <span class="math inline">\(\text{modell}_{11}\)</span>. Modellen räknas alltid ut genom att multiplicera radsumman för första variabeln med kolumnsumman för andra variabeln, och dividera resultatet med totala mängden observationer i datamaterialet <span class="math inline">\(n\)</span>.</p>
<p>För att exemplifiera detta kan vi ställa upp en kontingenstabell med påhittade siffror:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>datamatris <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">5</span>), <span class="at">nrow =</span> <span class="dv">2</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>datamatris</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    2    3
[2,]    7    5</code></pre>
</div>
</div>
<p>Med snabb huvudmatte kan vi räkna att vi har totalt <span class="math inline">\(n = 2+3+7+5 = 17\)</span> observationer. Sedan räknar vi rad- och kolumnsummorna för varje kombination:</p>
<p><span class="math display">\[\text{modell}_{11} = \frac{(2+3) * (2+7)}{17} = 2.647, \\
\text{modell}_{12} = \frac{(2+3) * (3+5)}{17} = 2.353, \\
\text{modell}_{21} = \frac{(7+5) * (2+7)}{17} = 6.353, \\
\text{modell}_{22} = \frac{(7+5) * (3+5)}{17} = 1.176\]</span></p>
<p>Efter detta slår vi in våra modellvärden i den slutliga formeln för <span class="math inline">\(\chi^2\)</span>:</p>
<p><span class="math display">\[\begin{equation}
\begin{split}
  \chi^2 &amp; = \sum_{i=1}^{n}\frac{(\text{observerat}_i-\text{modell}_i)^2}{\text{modell}_i} \\
  &amp; = \frac{(2-2.647)^2}{2.647} + \frac{(3-2.353)^2}{2.353} + \frac{(7-6.353)^2}{6.353} + \frac{(5-1.176)^2}{1.176} \\
  &amp; = 0.158 + 0.178 + 0.066 + 12.435 \\
  &amp; = 12.837
\end{split}
\end{equation}\]</span></p>
<p><span class="math inline">\(\chi^2\)</span>-testet har en frihetsgrad enligt följande formel: <span class="math inline">\(df = (r-1)(k-1)\)</span>, alltså mängden av rader minus ett multiplicerat med mängden av kolumner minus ett. Du kan även tänka dig formeln som mängden av kategorier i beroende variabeln, minus ett, multiplicerat med mängden av kategorier i oberoende variabeln, minus ett.</p>
<p>För vår exempelberäkning är <span class="math inline">\(df = (2-1)(2-1) = 1*1 = 1\)</span>.</p>
<p>Det slutliga värdet på <span class="math inline">\(\chi^2\)</span> varierar mellan 0-1. Testets storlek följer en <span class="math inline">\(\chi^2\)</span>-distribution (det var ju förvånande, det), så vi kan använda teststorleken för att få ett p-värde för nollhypotesen. De flesta <span class="math inline">\(\chi^2\)</span>-testfunktioner producerar detta p-värde färdigt, men om du inte har tillgång till p-värdet så kan du hämta ett värde med distributionsfunktionen <code>stats::pchisq(q, df)</code>, där argumentet <code>q</code> är värdet och <code>df</code> är frihetsgraden.</p>
<p>Vår beräkning ovan ger följande resultat:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fl">12.837</span>, <span class="at">df  =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9983689</code></pre>
</div>
</div>
<p>I R kan du utföra ett <span class="math inline">\(\chi^2\)</span>-test på två olika sätt. Om du har en färdig korstabell kan du kalla <code>base::summary()</code>-funktionen på den, vilket producerar testet:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(korstabell)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: xtabs(formula = ~alcgp + tobgp, data = esoph)
Number of cases in table: 88 
Number of factors: 2 
Test for independence of all factors:
    Chisq = 0.6195, df = 9, p-value = 0.9999
    Chi-squared approximation may be incorrect</code></pre>
</div>
</div>
<p>Du kan även kalla funktionen <code>stats::chisq.test()</code> på tabellen, vilket utför samma sak. Med denna kan du dock få ytterligare information om testet, vilket kan hjälpa dig undersöka robustheten:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>chi.kvadrat <span class="ot">=</span> <span class="fu">chisq.test</span>(korstabell)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(korstabell): Chi-squared approximation may be incorrect</code></pre>
</div>
</div>
<p>Ibland kan R kasta en varning i stilen av att “chi-kvadrat-approximeringen kan vara inkorrekt”. För <code>summary()</code>-funktionen står detta i output-texten. Detta innebär att en eller flera av de förväntande cellvärden underskrider 5, vilket brukar tas som en gräns för att lita på <span class="math inline">\(\chi^2\)</span>-testets robusthet. Du kan granska huruvida detta är sant genom att se på <code>chisq.test(data)$expected</code> (alla cellvärden borde vara större än 5):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>chi.kvadrat<span class="sc">$</span>expected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           tobgp
alcgp       0-9g/day    10-19    20-29      30+
  0-39g/day 6.272727 6.272727 5.227273 5.227273
  40-79     6.272727 6.272727 5.227273 5.227273
  80-119    5.727273 5.727273 4.772727 4.772727
  120+      5.727273 5.727273 4.772727 4.772727</code></pre>
</div>
</div>
<div class="extra-info" data-data_latex="">
<div class="left-adj" data-data_latex="">
<p><strong>Förväntande värden under fem?</strong></p>
</div>
<p>Om du har problem med för låga förväntande värden, borde du i första hand samla mera data eller godkänna ditt öde. Det finns dock ett antal andra test som kan utföras på sådana datafördelningar.</p>
<ul>
<li><strong>Fishers exakta test</strong> fungerar på 2x2-tabeller, alltså korstabeller där bägge variabel är binär. Testet kan även räknas på större tabeller, men var förberedd på långa kalkylationstider. Använd funktionen <code>stats::fisher.test(data)</code>.</li>
<li><strong>Likelihood ratio</strong> fungerar som <span class="math inline">\(\chi^2\)</span>-testet, men är robust för små urvalsstorlekar, alltså situationer där du kan finna förväntade cellfrekvenser under fem. R har ingen funktion för att kalkylera likelihood ratio för en korstabell. [LETA REDA PÅ EN!]</li>
<li><strong>Cramérs V-test</strong> fungerar lite annorlunda än de andra testen, eftersom det ger en direkt effektstorlek. V varierar mellan 0-1 och är jämförbar med traditionella korrelationskoefficienter (mera om dem senare). Detta gör V-testet till ett mycket användbart test, och det är faktiskt att föredra att rapportera V om du vill jämföra effektstorleken med effekten i ett test som inte härstammar från en korstabell. Om du vill jämföra mellan korstabeller kan du alltid jämföra procentuella förändringar. Använd funktionen <code>DescTools::CramerV(data)</code>. Du kan även hämta bootstrap-konfidensintervall för V med argumentet <code>conf.level=x</code>, där <code>x</code> är din konfidensnivå (t.ex. 0.95). Notera att detta kan ta en stund!</li>
</ul>
</div>
<p>För visualisering av korstabeller kan vi förstås trycka själva tabellen, och detta är ett standardiserat sätt att uttrycka resultaten. Däremot kan vi även ställa upp resultaten grafiskt, med hjälp av en <strong>mosaikgraf</strong>. Mosaikgrafen uttrycker korstabellens frekvenser som en tvådimensionell “låda”. Du kan generera en mosaikgraf med funktionen <code>graphics::mosaicplot(data)</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaicplot</span>(datamatris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="bivariat-analys_files/figure-html/mosaic-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Från grafen syns de relativa frekvenserna av varje kategori för rader och kolumner. Ta till exempel rad 1, kolumn 1 (cell 1.1): den tycks stå för ungefär en tredjedel av alla observationer på rad 1, och två femtedelar eller så av alla observationer i kolumn 1. Vi kan använda grafen för att få en snabb syn på huruvida vi tror att den oberoende variabeln (kolumnerna) är relaterad till den beroende variabeln (raderna). I vårt fall kunde det kanske ha varit så, eftersom cellstorlekarna är väldigt annorlunda (vilket innebär olika relativa frekvenser inom kategorierna), men vårt <span class="math inline">\(\chi^2\)</span>-test föreslog redan att detta trots allt inte var fallet.</p>
<p>Eftersom vårt <span class="math inline">\(\chi^2\)</span> uppvisade problem med de förväntade cellerna, kan vi använda Fishers exakta test för att få robusta resultat. Trots att testet är gjort för 2x2-tabeller går det att göra på större tabeller än så, och i vårt fall är analysen ännu någorlunda snabb:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(datamatris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  datamatris
p-value = 0.6199
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.03039342 6.17614082
sample estimates:
odds ratio 
 0.4978506 </code></pre>
</div>
</div>
<div class="page-columns page-full"><p>P-värdet är 0.6199, vilket är högre än en rimlig alfatröskel (t.ex. <span class="math inline">\(\alpha = 0.05\)</span>), så vi kan inte förkasta nollhypotesen. Med andra ord: ett testvärde på detta (0.498) eller större är 62 % sannolikt om det riktiga testvärdet vore 1<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Vår grafiska intution skulle ha fört oss fel!</p><div class="no-row-height column-margin column-container"><li id="fn3"><p><sup>3</sup>&nbsp;I detta fall testar vi <em>odds ratio</em>, vars “nolläge” är 1 istället för 0. För mera information, se kapitel XXX.</p></li></div></div>
<div class="functions-summary" data-data_latex="">
<div class="left-adj" data-data_latex="">
<p><strong>Funktioner:</strong></p>
</div>
<ul>
<li><code>xtabs(formula, data)</code>: Skapar en korstabell. Argumentet <code>formula</code> tar en formel på vad som ska korstabuleras, och <code>data</code> tar en mångdimensionell datastruktur. Formeln kan innehålla andra kontroller, se hjälpfunktionen <code>?xtabs</code> för mer information.</li>
<li><code>pchisq(värde, df)</code>: Returnerar p-värdet för ett värde på <span class="math inline">\(chi^2\)</span> med frihetsgraden <code>df</code>. Märk, att funktionen inte beaktar om kraven för <span class="math inline">\(\chi^2\)</span> har uppfyllts!</li>
<li><code>chisq.test(data)</code>: Utför ett <span class="math inline">\(\chi^2\)</span>-test på <code>data</code>. Returnerar många olika statistiker, varav <code>$expected</code> är nyttig för att granska att alla förväntade cellvärden är över fem.</li>
<li><code>fisher.test(data)</code>: Utför Fishers exakta test på <code>data</code>.</li>
<li><code>CramerV(data)</code>: Räknar Cramérs V-test för <code>data</code>. För konfidensintervall, ge argumentet <code>conf.level = x</code>, där <code>x</code> är din konfidensnivå (t.ex. 0.95). Märk att beräkningen kan haka sig fast ibland, p.g.a. bootstrapping.</li>
<li><code>mosaicplot(data)</code>: Ritar en mosaikgraf på <code>data</code>. Användbar för att snabbt granska huruvida korstabellen kunde vara värd att undersöka.</li>
</ul>
</div>
</section>
</section>
<section id="students-t-test" class="level2 page-columns page-full" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="students-t-test"><span class="header-section-number">12.2</span> Students T-test</h2>
<p>Korstabeller fungerar mycket bra för bivariata förhållanden mellan två kvalitativa variabler, men vad gör vi när ena variablen är kvantitativ? Svaret beror på vilken av våra variabler. Om vår beroende variabel är kvantitativ, men vår oberoende variabel är kvalitativ, så använder vi <strong>t-testet</strong>. Om situationen är tvärtemot, använder vi <strong>logistisk regression</strong> (vilket förklaras i samband med multivariata analyser).</p>
<p><strong>Students t-test</strong> är skapat av statistikern William Sealy Gosset (1876-1937). Namnet kommer från att Gosset publicerade under pseudonymen “Student”, och termen “t-test” är egentligen lite fel: Gosset kallade testet för “t-statistiken”, vilket stod för “hypotesteststatistiken”. Vi fortsätter kalla det t-testet, eftersom namnet är välkänt, men märk att förkortningen då står för “hypotestesttestet”.</p>
<p>T-testet mäter huruvida en skillnad kan anses vara tillräckligt stor för att den inte kunde orsakas under en nollhypotes - därför namnet “hypotestestet”. Vad denna skillnad är, och vilken nollhypotes som testas, beror på situationen. Vi kan tala om t-test för enkla urval och t-test för dubbla urval (eng. <em>one- and two-sample t-tests</em>).</p>
<p>Oavsett urvalsform följer t-testet en t-fördelning:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="bivariat-analys_files/figure-html/t-distribution-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Som du märker är t-fördelningen väldigt lik normalfördelningen. Den största skillnaden är att t-fördelningen har större <em>svansar</em>, alltså är den lite mera sensitiv för extrema värden.</p>
<p>På grund av att t-testet följer en fördelning, kan vi hämta sannolikhetsvärden för att en skillnad ger ett visst testvärde. För att göra detta bör vi även bestämma om vi testar <em>två- eller ensidigt</em>. Ett ensidigt t-test räknar ut sannolikheten att värdet är antingen större än, eller mindre än, det förväntade värdet. Du måste välja vilkendera du förväntar dig. Ett tvåsidigt t-test, å andra sidan, räknar ut sannolikheten att värdet <em>skiljer sig</em> från det förväntade värdet, oavsett vilken riktning. Dessa är något olika alternativa hypoteser, och påverkar tröskelvärdet för t-statistiken. Välj därför rätt!</p>
<section id="t-test-för-enkla-urval" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="t-test-för-enkla-urval"><span class="header-section-number">12.2.1</span> T-test för enkla urval</h3>
<p>Om vi testar skillnaden mellan ett urval och det förväntade populationsvärdet, talar vi om ett <em>t-test för ett urval</em> (eng. one-sample t-test). Då beräknas t-testet så här:</p>
<p><span class="math display">\[\begin{equation}
\text{t} = \frac{\bar{x} - \mu}{\text{SD}/\sqrt{n}}
\end{equation}\]</span></p>
<p>och i vanligt språk: t-statistiken är lika med det mätta medeltalet subtraherat med populationsmedeltalet, dividerat med standardavvikelsen dividerad med kvadratroten av urvalsstorleken.</p>
<p>Vi kan använda t-testet för enkla urval för att beräkna huruvida ett mätt medeltal är så pass mycket större (eller mindre) än något förväntat värde, att vi kan förkasta nollhypotesen att värdet är det förväntade värdet. Kom ihåg att välja om du vill testa för riktning (ensidigt) eller bara skillnad (tvåsidigt).</p>
<p>Ett t-test för enkla urval kan utföras enkelt (ha!) i R med funktionen <code>t.test()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>       y,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="fu">c</span>(<span class="st">"two-sided"</span>, <span class="st">"less"</span>, <span class="st">"greater"</span>),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">FALSE</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">FALSE</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>       ...)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Argumentet <code>x</code> står för de data du vill testa. <code>y</code> är inte nödvändigt för t-test för enkla urval, men skulle användas för att testa skillnaden med andra data. <code>alternative</code> används för att bestämma hurudant test du gör: “two-sided” för tvåsidat test, “less” eller “greater” för ensidade test, antingen lägre än gränsvärdet eller högre än gränsvärdet. Med argumentet <code>mu</code> kan du ändra på vad nollhypotesen är; ofta testar du mot noll, men du kan byta det till vilken siffra som helst (enligt vad en logisk nollhypotes är för ditt syfte). <code>paired</code> används för att göra ett parat t-test - mer om detta senare. Argumentet <code>var.equal</code> bestämmer huruvida du gör ett test som är robust för variansheterogenitet eller inte. Till sist, <code>conf.level</code> bestämmer vilken konfidensnivå du vill använda. 0.95 motsvarar <span class="math inline">\(\alpha = 0.05\)</span>, men du kan ändra konfidensnivån enligt behov.</p>
<p>Vi kan göra ett exempel. Säg att vi har mätt en massa data och vill veta om medeltalet på detta data skiljer sig statistiskt från 0, oavsett riktning. Eftersom vi inte är intresserade av riktning är det fråga om ett tvåsidigt test, och eftersom vi testar emot noll behöver vi inte ändra på <code>mu</code>-argumentet. Konfidensnivån håller vi på den vanliga 0.95-nivån, så vi behöver inte ändra på den heller.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>testdata <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="fl">2.5</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(testdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  testdata
t = 22.175, df = 99, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 2.189935 2.620354
sample estimates:
mean of x 
 2.405145 </code></pre>
</div>
</div>
<p>Märk att jag inte behövde ge några som helst argument, förutom mitt data, åt <code>t.test()</code>. Detta är eftersom vi använde alla standardargument - vi gjorde tvåsidigt test mot nollhypotesen att värdet är 0, och vi bad om p-värde enligt konfidensnivån 0.95.</p>
<p>Testresultatet berättar åt oss att det är frågan om ett T-test för enkelt urval (se rubriken). Vi får även veta våra storlekar: <span class="math inline">\(\text{t} = 27.131, \text{df} = 99, \text{p} = 2.2 * 10^{-16}\)</span>. Testet berättar åt oss även det testade medeltalet, <span class="math inline">\(\hat{x} = 2.60\)</span>, samt dess konfidensintervall på 0.95-nivån, <span class="math inline">\(\text{95% CI} = [2.41;2.80]\)</span>. Därutöver säger den vad vi testade emot (“true mean is not equal to 0”), ifall vi lyckas glömma det.</p>
<div class="extra-info" data-data_latex="">
<div class="left-adj" data-data_latex="">
<p><strong>Varför finns det bokstäver i mitt p-värde?!</strong></p>
</div>
<p>När vi jobbar med siffror hamnar vi ofta jobba med väldigt stora eller väldigt små siffror. Tänk dig att du ofta skulle jobba med siffror i miljardstorleken eller större (t.ex. statliga ekonomier eller hjärnceller). Det skulle bli väldigt svårt om din text är pepprad med siffror så som 1 000 000 000, 26 583 397 236 och 236 347 000.</p>
<p>För att underlätta läsningen använder vetenskapsidkare ofta <strong>vetenskaplig notation</strong> av siffror. Exempel siffrorna ovan kan skrivas på två sätt med vetenskaplig notation:</p>
<ol type="1">
<li><span class="math inline">\(1.0 * 10^9, 26.5 * 10^9, 0.2*10^9\)</span></li>
<li><span class="math inline">\(1.0\text{e}9, 26.5\text{e}9, 0.2\text{e}9\)</span></li>
</ol>
<p>Detta förkortar siffrorna till en liten siffra, gånger en potens av tio. Du kan läsa dem som att potensstorleken (9 i exemplet) berättar åt dig hur många steg åt vänster du ska skuffa decimaltecknet. För att komma från 1.0 till en miljard ska du skuffa decimaltecknet 9 steg åt vänster, och lägga till nollor anefter. Bokstaven “e” i andra exemplet kan avläsas som “exponent”, alltså en förkortning för “tio upphöjt i…”</p>
<p>En annan vanlig situation där du bemöter vetenskaplig notation är med p-värden, eftersom de blir otroligt små. Samma sak gäller här, förutom att ett negativt tecken används för att påvisa att siffran är mindre än 1. Därmed är <span class="math inline">\(0.05\)</span> samma sak som <span class="math inline">\(5*10^{-2}\)</span>, och <span class="math inline">\(0.000000635\)</span> samma sak som <span class="math inline">\(6.3 * 10^{-7}\)</span>. Skuffa decimaltecknet åt höger istället för åt vänster.</p>
<p>Det kan vara nyttigt att lära dig några vanliga tröskelvärden i vetenskaplig notation:</p>
<ul>
<li><span class="math inline">\(p = 0.05 = 5*10^{-2}\)</span></li>
<li><span class="math inline">\(p = 0.01 = 1*10^{-2}\)</span></li>
<li><span class="math inline">\(p = 0.001 = 1*10^{-3}\)</span></li>
</ul>
</div>
</section>
<section id="t-test-för-dubbla-urval" class="level3 page-columns page-full" data-number="12.2.2">
<h3 data-number="12.2.2" class="anchored" data-anchor-id="t-test-för-dubbla-urval"><span class="header-section-number">12.2.2</span> T-test för dubbla urval</h3>
<div class="page-columns page-full"><p>Vi kan även använda t-testet för att testa skillnaden mellan två grupper i vårt urval. Detta kallas för ett t-test för dubbla urval, men trots namnet behöver du inte ha två separata urval. Vad testet gör är att det egentligen testar om de två grupperna härstammar från <em>samma</em> population. Detta gör att vi kan testa avsaknaden av olikhet<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> mellan dessa två grupper.</p><div class="no-row-height column-margin column-container"><li id="fn4"><p><sup>4</sup>&nbsp;Se nedan för likhetstestning för att förstå varför avsaknaden av olikhet inte är detsamma som likhet.</p></li></div></div>
<p>T-testet för dubbla urval ser ut på detta vis:</p>
<p><span class="math display">\[\begin{equation}
\text{t} = \frac{\bar{x}_1-\bar{x}_2}{\sqrt{\frac{\text{s}^2_1}{\text{n}_1}+\frac{\text{s}^2_2}{\text{n}_2}}}
\end{equation}\]</span></p>
<p>I klarspråk: Börja med att subtrahera medeltal 2 från medeltal 1. Sedan dividerar du det med följande: kvadratroten av, summan av varians 1 dividerat med urvalsstorlek 1 och varians 2 dividerat med urvalsstorlek 2.</p>
<p>Detta test är faktiskt en mer robust form av dubbla urvalstestet, som kallas <strong>Welch t-test</strong>. Testet uppfanns av Bernard Lewis Welch, och modifierar det ursprungliga t-testet något. Till skillnad från de andra testen är denna variant av t-testet robust för olika gruppstorlekar <em>och</em> olika stora varianser. Det finns en orsak varför du inte skulle vilja använda Welch T-test: det är inte reliabelt i små urvalsstorlekar. Men, samma gäller för nästan alla bivariata test, så jag skulle inte ta huvudbry av det. Om du har för litet urval, samla mera data.</p>
<p>Det dubbla t-testet utför du med samma funktion som tidigare, <code>t.test()</code>! Det är faktiskt så, att R utför Welch version av testet automatiskt - väldigt behändigt. Skillnaden till tidigare är att du nu ska ge testet <em>två</em> variabler (eftersom du ju testar skillnaden mellan två variabler), vilka ges med argumenten <code>x</code> och <code>y</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> testdata</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> a, <span class="at">y =</span> b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  a and b
t = 17.275, df = 114.3, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 1.722034 2.168135
sample estimates:
mean of x mean of y 
2.4051447 0.4600603 </code></pre>
</div>
</div>
<p>Resultatet ser väldigt lika ut som för det enkla urvalets t-test, förutom att rubriken nu säger “Welch Two Sample t-test”. Testet berättar även åt oss vad vår alternativa hypotes denna gång är, samt att vi använde objekten <code>a</code> och <code>b</code> för vår analys. Vårt p-värde är väldigt lågt, och tydligt under en ordinarie gräns på <span class="math inline">\(5*10^{-2}\)</span>. Vi kan därmed med god sannolikhet förkasta vår nollhypotes: det vore väldigt sällsynt att få dessa resultat eller större om det faktiskt vore så, att bägge medeltal är desamma (alltså att skillnaden mellan dem är noll).</p>
</section>
<section id="rapportering-av-t-test" class="level3" data-number="12.2.3">
<h3 data-number="12.2.3" class="anchored" data-anchor-id="rapportering-av-t-test"><span class="header-section-number">12.2.3</span> Rapportering av t-test</h3>
<p>Ett t-test har tre viktiga kvantitativa mått: t-statistiken, frihetsgraderna och p-värdet. Alla tre bör rapporteras när du har gjort ett t-test. Utöver dessa kan konfidensintervallet vara bra om det finns en chans att resultatet upprepas och används i meta-analyser. Om du har gjort ändringar åt <code>mu</code>-koefficienten (gränsvärdet som testas emot) ska du rapportera det, annars förmodar läsare att du har testat emot noll:</p>
<p><em>Skillnaden mellan X och Y på vår oberoende variabel är inte signifikant (t = 0.5, df = 12, p = 0.687).</em></p>
<p><em>Welch robusta t-test visade på en signifikant skillnad mellan variablerna X och Y (t = 20.9, df = 117.28, p = 2 x 10^16, 95% CI av skillnaden [1.9; 2.3].</em></p>
<p>Det finns inte några etablerade sätt att ställa upp ett t-test grafiskt, eftersom det enbart handlar om ett osäkerhetsmått (och dessa inte är lika intressanta som effektmåtten). Det är oftast bättre att rapportera t-testet i text, eftersom det är ett enkelt text med få delar att förstå. Du kan förvisso skapa lådgrafer av variablerna du jämförde, för att göra skillnaden visuellt tydlig. Kom dock ihåg att ställa in samma skala åt graferna, så att de faktiskt är jämförbara:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(a, b)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> df<span class="sc">$</span>a)) <span class="sc">+</span> <span class="fu">coord_cartesian</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> df<span class="sc">$</span>b)) <span class="sc">+</span> <span class="fu">coord_cartesian</span>(<span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>p1 <span class="sc">|</span> p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="bivariat-analys_files/figure-html/t-test-reporting-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="likhetstest-och-minimistorlekstest" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="likhetstest-och-minimistorlekstest"><span class="header-section-number">12.3</span> Likhetstest och minimistorlekstest</h2>
<p>Ett traditionellt vetenskapligt ordspråk lyder: <em>Avsaknaden av bevis är inte bevis för avsaknad</em>. Med andra ord: bara för att du inte finner en endaste svart svan, betyder det inte att de inte finns.</p>
<p>Detta medför ett litet problem till nollhypotessignifikanstestning: förkastande av nollhypotesen är inte bevis för alternativa hypotesen. Då du utför t.ex. ett t-test eller chi-kvadrat, och får ett signifikant värde, betyder det endast att det resultat du fått vore <em>osannolikt</em> (på din alfanivå, t.ex. 0.05) <em>om</em> det faktiskt vore så, att den verkliga skillnaden var noll. Detta säger inget om huruvida ditt resultat är sant.</p>
<p>Mer allmänt har detta varit ett problem för NHST: vetenskapsidkare vill ofta säga något om deras bevis, men NHST säger bara något om hypotesen. Lösningen, som tidigare sagt, kan vara Bayesisk statistik - istället för att undersöka hypotesens sannolikhet under data, kan man undersöka datas sannolikhet under hypotesen.</p>
<p>Ett annat problem är vad som menas med “avsaknad”. På grund av mätfel har alla statistiska urval någon nivå av variation, vilket innebär att alla skillnader kommer att vara något ovan noll. Det kan handla om mycket små skillnader från noll, men trots allt skillnader från noll. Detta leder ofta till Typ I och Typ II fel (se kapitel @ref(statistisk-inferens)). Detta är ett problem både om vi vill testa ifall skillnaden är noll och om vi testar ifall skillnaden är annat än noll.</p>
<p>Ett nyutvecklat verktyg, som behåller NHST-filosofin men möjliggör påståenden om avsaknad, är <strong>likhets- och minimistorlekstestning</strong>. Med dessa kan vi beakta den naturliga variationen av våra skillnadstest, och ändå säga något om den <em>relevanta</em> skillnaden vi undersöker. Dessa test utgörs av två olika, men relaterade test.</p>
<p>Ett <strong>likhetstest</strong> (eng. <em>equivalence test</em>) testar huruvida två mätta medeltal är lika stora inom en viss likhetsgräns. Det är baserat på TOST-proceduren (eng. <em>two one-sided T-tests</em>), och görs genom att testa två olika hypoteser:</p>
<ul>
<li>Nollhypotes 1: Skillnaden mellan medeltalen är större än A.</li>
<li>Nollhypotes 2: Skillnaden mellan medeltalen är mindre än B.</li>
</ul>
<p>Vad vi gör i ett likhetstest, är att vi bestämmer ett intervall runt noll som innebär att skillnaden <em>praktiskt taget</em> är lika. Vad ska detta intervall vara? Det beror på vad vi mäter! TOST-proceduren inskriver en grad av subjektivitet i likhetstestning, men detta är inte dåligt. All statistik innehåller subjektiva omdömen, men i detta test gör vi det explicit.</p>
<p>Efter att vi beräknat ensidiga T-test för dessa två hypoteser granskar vi deras signifikans (på den nivå vi förbestämt). Om bägge är signifikanta, kan vi säga att sannolikheten att få så pass likadana resultat som vi har fått är mycket låg om det vore så, att skillnaden i verkligheten är större/mindre än våra gränser.</p>
<p>Ett <strong>minimieffekttest</strong> (eng. <em>minimal effect test</em>) är mycket likadant, men nu testar vi åt andra hållet:</p>
<ul>
<li>Nollhypotes 1: Skillnaden mellan medeltalen är mindre än A.</li>
<li>Nollhypotes 2: Skillnaden mellan medeltalen är större än B.</li>
</ul>
<p>Med andra ord: nollhypoteserna påstår tillsammans att skillnaden ligger <em>inom</em> våra gränsen, inte utanför. Vi använder minimieffekttestet, så som namnet föreslår, för att testa huruvida skillnaden är praktiskt taget relevant, enligt de gränser vi lägger.</p>
<p>Om du är klipsk, så märkte du säkert att minimieffekttestet är bara motsatsen av likhetstestet. Så är det! Orsaken till att vi behöver testet är aforismen jag nämnde tidigare: avsaknaden av bevis är inte bevis för avsaknad. Om ett likhetstest är icke-signifikant kan vi inte dra slutsatsen att skillnaden vi mätte är olika från noll, endast att det är <em>sannolikt</em> att få en sådan skillnad även då en sådan skillnad inte faktiskt finns. Detta kan te sig svårt att förstå, så kom åtminstone ihåg följande: <strong>avsaknaden av bevis är inte bevis för avsaknad</strong>. Ett hypotestest berättar endast om datas sannolikhet under nollhypotesen. Om du vill säga något om en alternativ hypotes, måste du omforma den till en ny nollhypotes.</p>
<p>Likhets- och minimieffekttest kan göras enkelt med paketet <code>TOSTER</code>. I paketet finns funktionen <code>t_TOST()</code>, vilken tar nästan alla samma argument som <code>t.test</code>. Två nya argument är dock viktiga:</p>
<ul>
<li><code>eqb</code>: Storleken på likhetsgränsen, i en siffra. Detta skapar ett symmetriskt intervall runt jämförelsevärdet. Om du t.ex. testar likhet (skillnad = 0) med <code>eqb = 0.5</code>, så skapar den ett intervall på [-0.5, 0.5].</li>
<li><code>hypothesis</code>: Antingen “EQU” för likhet (equivalence) eller “MET” för minimieffekttest.</li>
</ul>
<p>Du kan även beakta olika varianser, ändra alfanivå, ändra <code>mu</code>, samt göra andra, mer avancerade ändringar till testet. Som exempel vill jag göra ett minimiskillnadstest på de data vi tidigare använde, med likhetsintervallet [-0.5, 0.5]:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t_TOST</span>(<span class="at">x =</span> df<span class="sc">$</span>a,</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> df<span class="sc">$</span>b,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">hypothesis=</span><span class="st">"MET"</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">var.equal=</span><span class="cn">FALSE</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">eqb =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Welch Two Sample t-test

The minimal effect test was significant, t(114.3) = 21.715, p = 3.41e-24
The null hypothesis test was significant, t(114.3) = 17.275, p = 1.19e-33
NHST: reject null significance hypothesis that the effect is equal to zero 
TOST: reject null MET hypothesis

TOST Results 
               t    df p.value
t-test     17.27 114.3 &lt; 0.001
TOST Lower 21.72 114.3       1
TOST Upper 12.83 114.3 &lt; 0.001

Effect Sizes 
               Estimate     SE             C.I. Conf. Level
Raw               1.945 0.1126 [1.7584, 2.1318]         0.9
Hedges's g(av)    2.427 0.4500  [2.0727, 2.774]         0.9
Note: SMD confidence intervals are an approximation. See vignette("SMD_calcs").</code></pre>
</div>
</div>
<p>Resultatet är tredelat: Först skriver testet ut en massa information i konsolen. Sedan ger den en dataram med T-statistikerna (<code>resultat$TOST</code>), och sedan en dataram med estimerade effektstorlekar (<code>resultat$effsize</code>). När vi läser av resultatet räcker det med konsolutskriften, men om du vill spara resultaten kan du senare använda t.ex. effektstorlekarna i grafiska uppsättningar.</p>
<p>Att tolka en TOST-procedur är lite mer komplext än ett vanligt t-test. Det första att komma ihåg är att det är frågan om <em>två</em> ensidiga t-test. [HUR TOLKAS DETTA?]</p>
</section>
<section id="korrelationsanalys" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="korrelationsanalys"><span class="header-section-number">12.4</span> Korrelationsanalys</h2>


</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./univariat-analys.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Univariat analys</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./källförteckning.html" class="pagination-link">
        <span class="nav-page-text">Källförteckning</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>