<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="“Människovetaren och statistiken” är en grundkurs i den statistiska analysens process, ämnad för universitetsstuderande i samhälls- och humanvetenskaper. Målet är att göra statistisk analys tillgänglig och begriplig, och att minska studentens statistikångest genom att synliggöra hur statistik egentligen är likt all annan forskning, fastän med siffror. Boken är en work-in-progress, med början den 12:e februari 2023.">

<title>Människovetaren och statistiken - 9&nbsp; R, del två</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./grafik.html" rel="next">
<link href="./grundläggande-kunskaper-i-programmering.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">R, del två</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Människovetaren och statistiken</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Förord</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Analysens logik</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vad-är-statistik.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Vad är statistik?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vad-är-data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Vad är data?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./från-ide-till-rapport.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Från idé till rapport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./variabler.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variabler</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modeller.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modeller</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistisk-inferens.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Statistisk inferens</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">R-miljön</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduktion-till-r-miljön.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduktion till R-miljön</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./grundläggande-kunskaper-i-programmering.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Grundläggande kunskaper i R-programmering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-del-två.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">R, del två</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./grafik.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Grafik</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Statistiska metoder</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./univariat-analys.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Univariat analys</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariat-analys.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bivariat analys</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./källförteckning.html" class="sidebar-item-text sidebar-link">Källförteckning</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#paket" id="toc-paket" class="nav-link active" data-scroll-target="#paket"><span class="toc-section-number">9.1</span>  Paket</a>
  <ul class="collapse">
  <li><a href="#installera-och-aktivera-paket" id="toc-installera-och-aktivera-paket" class="nav-link" data-scroll-target="#installera-och-aktivera-paket"><span class="toc-section-number">9.1.1</span>  Installera och aktivera paket</a></li>
  </ul></li>
  <li><a href="#data-in-och-ut-ur-r" id="toc-data-in-och-ut-ur-r" class="nav-link" data-scroll-target="#data-in-och-ut-ur-r"><span class="toc-section-number">9.2</span>  Data in och ut ur R</a>
  <ul class="collapse">
  <li><a href="#spss" id="toc-spss" class="nav-link" data-scroll-target="#spss"><span class="toc-section-number">9.2.1</span>  SPSS</a></li>
  <li><a href="#csv" id="toc-csv" class="nav-link" data-scroll-target="#csv"><span class="toc-section-number">9.2.2</span>  CSV</a></li>
  <li><a href="#andra-format" id="toc-andra-format" class="nav-link" data-scroll-target="#andra-format"><span class="toc-section-number">9.2.3</span>  Andra format</a></li>
  <li><a href="#övning-läs-in-barometerdata-till-r" id="toc-övning-läs-in-barometerdata-till-r" class="nav-link" data-scroll-target="#övning-läs-in-barometerdata-till-r"><span class="toc-section-number">9.2.4</span>  Övning: Läs in barometerdata till R</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">R, del två</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Detta kapitel handlar om några ytterligare nödvändiga kunskaper i R: att aktivera paket och att jobba med externa data. Efter detta kapitel är du redo att börja generera en massa grejer i R - men oroa dig inte om du inte har förstått allt ännu. Programmering tar en stund att bli van med, och det kräver mycket övning.</p>
<section id="paket" class="level2 page-columns page-full" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="paket"><span class="header-section-number">9.1</span> Paket</h2>
<p>R-språket kan förstås som en bas, lite liknande som grunderna i ett naturligt språk. Du kan göra en hel del med grunderna, uttrycka grundläggande meningar och kanske även klara dig relativt långt i kommunikation. Snabbt når du dock en vägg, där språket inte räcker till. För att utvidga språket lär du dig nya semantiska register, samlingar av ord som alla tillhör något visst område. Du kanske lär dig naturvetenskapliga ord, eller IT-relaterade ord, eller ord om familjelivet.</p>
<p>På samma sätt har R olika “register”, vilka kallas för <strong>paket</strong>. I själva verket är basinstallationen av R uppbyggd av paket. I <code>Packages</code>-tabben i RStudio kan du se vilka paket som finns installerade samt aktiverade i din R-instans. Du kan även hämta en vektor med alla aktiva paket genom att köra kommandot <code>base::loadedNamespaces()</code>. Några viktiga paket som kan hjälpa dig i dina studier är:</p>
<ul>
<li><code>datasets</code>: Ett stort antal olika dataset som du kan använda i övningssyften.</li>
<li><code>graphics</code>: Grundläggande grafikverktyg för datavisualisering.</li>
<li><code>foreign</code>: Verktyg för att läsa in data från olika filformater, bl.a. SPSS- och Stata-filer.</li>
<li><code>stats</code>: Grundläggande statistiska modeller och testverktyg.</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>base::loadedNamespaces()</code>: Returnerar vektor med alla aktiva paket.</p>
</div></div><div class="extra-info">
<div class="center">
<p><strong>Masking</strong></p>
</div>
<p>Vad händer om du har två funktioner med samma namn från olika paket? Enkelt sagt: R tolkar kommandot som att det tillhör den senare aktiverade.</p>
<p>Låt oss säga att vi har två paket, <code>A</code> och <code>B</code>, som båda innehåller en funktion med samma namn, <code>f()</code>. Om du aktiverar paket <code>A</code> först och paket <code>B</code> sedan, och kör <code>f()</code>, så kommer R att köra versionen från <code>B</code>. Om du aktiverar <code>B</code> först och <code>A</code> sedan, kör R versionen från <code>A</code>.</p>
<p>Hur kommer man runt detta? Det lättaste sättet är att köra <strong>explicita</strong> kommandon. Dessa skrivs i formen <code>paket::funktion()</code>. Detta säkrar att du kör funktionen från det paket du vill köra från.</p>
</div>
<section id="installera-och-aktivera-paket" class="level3 page-columns page-full" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="installera-och-aktivera-paket"><span class="header-section-number">9.1.1</span> Installera och aktivera paket</h3>
<div class="page-columns page-full"><p>Paket laddas ned från CRAN<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, på samma sätt som basinstallationen av R. Men du behöver inte gå på nätet och söka efter suspekta <code>.exe</code>-filer - du kan installera paket direkt ur R!</p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;De kan även laddas ned och byggas från t.ex. GitHub, men vi håller oss till CRAN-paket i denna bok.</p></li></div></div>
<p>Funktionen <code>install.packages(*paket)</code> låter dig installera paket på två olika sätt. Du kan köra funktionen utan argument <code>install.packages()</code>, vilket öppnar en meny med alla paket du kan installera från CRAN. Detta är dock väldigt många, och det kan vara svårt att hitta paketet du söker efter. Alternativt kan du köra funktionen med paketets namn som argument, t.ex. <code>install.packages(ppcor)</code>. Detta exempel installerar paketet <code>ppcor</code>, vilket innehåller funktioner för partiella och delkorrelationer.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>utils::install.packages(paket)</code>: Installerar paketet <code>paket</code> från CRAN. Ber dig välja CRAN-server om den inte redan är vald.</p>
</div></div><p>För att ladda ned ett paket <em>samt</em> alla de subpaket paketet kräver för att fungera, använd argumentet “dependencies”: <code>install.packages("ppcor", dependencies=TRUE)</code>.</p>
<p>Du behöver endast installera ett paket en gång, så du har inget behov att köra funktionen varje gång du öppnar R. Däremot måste du <strong>aktivera</strong> ett paket varje gång du vill använda det i en unik R-instans. När du aktiverar ett paket dyker det upp i vektorn som <code>loadedNamespaces()</code> producerar, och då är alla paketets funktioner äntligen användbara.</p>
<p>Du kan aktivera ett paket i RStudio genom att trycka för checkboxen bredvid paketets namn. I kod kan du aktivera ett paket med funktionen <code>library(paket)</code>. Märk att ordningen av paketens aktivering kan påverka vilken funktion som blir aktiv i en situation där du har dubbletter!</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>base::library(paket)</code>: Aktiverar paketet <code>paket</code>. Paketet måste vara installerat först.</p>
</div></div></section>
</section>
<section id="data-in-och-ut-ur-r" class="level2 page-columns page-full" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="data-in-och-ut-ur-r"><span class="header-section-number">9.2</span> Data in och ut ur R</h2>
<p>Klappa dig själv på axeln, du har kommit långt i din R-inlärning! Till nästa lär vi oss hur du får data in i och ut ur R-miljön. Detta är väldigt viktigt, eftersom du ju behöver dina data för att kunna utföra data-analys.</p>
<p>Grunderna i att läsa in data är faktiskt väldigt lätta: <code>mina_data &lt;- dataläsningsfunktion()</code>. Med andra ord skapar du ett objekt för dina data, och sedan tilldelar du dina data till objektet genom en dataläsningsfunktion. Hur detta exakt görs beror på typen av dina data. Övningsdatafilen vi använder är av formatet <code>csv</code>, men du kan även läsa in andra typer av data än just det. Ett populärt format är SPSS-filer, så första kapitlet handlar om dem.</p>
<section id="spss" class="level3 page-columns page-full" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="spss"><span class="header-section-number">9.2.1</span> SPSS</h3>
<p>Ett mycket vanligt verktyg för statistisk analys bland människovetare är <em>IBM SPSS Statistics</em>. Eftersom vi jobbar i R i denna bok, vill jag välkomna användare av SPSS att byta och se ljuset. Trots detta kommer ändå du, kära läsare, att garanterat bemöta SPSS i en form eller annan i framtiden. Då kan du briljera med hur enkelt det är att läsa in SPSS-data i R, köra dina fina analyser och skapa ännu finare grafiska upplägg, och exportera till olika filformat.</p>
<p>Tidyverse-paketet <code>readr</code> innehåller behändiga verktyg för hantering av SPSS-datafiler, både i formaten <code>sav</code> och <code>por</code>. För läsning av SPSS-filer, använd funktionerna <code>read_sav(path)</code> och <code>read_por(path)</code>. Bägge funktion fungerar på samma sätt, ge dem filadressen för filen som ska läsas, samt valfria ytterligare argument. Nedan är några behändiga argument:</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>readr::read_sav(path, ...)</code>: Läser in data från en <code>.sav</code>-fil. För övriga inställningar, se hjälpfunktionen <code>?read_sav</code>. <code>readr::read_por(path, ...)</code>: Läser in data från en <code>.por</code>-fil. För övriga inställningar, se hjälpfunktionen <code>?read_por</code>.</p>
</div></div><ul>
<li><code>encoding</code>: Om filen använder en speciell teckenkodning, eller om det inte går att läsa teckenkodningen automatiskt från filen, så kan du specificera den med detta argument.</li>
<li><code>user_na</code>: Huruvida användarspecificerade saknande koder ska kodas till egna faktornivåer (<code>TRUE</code>) eller konverteras till <code>NA</code> (<code>FALSE</code>). Det är rekommenderat att använda <code>NA</code> inom R om du inte absolut måste använda något annat, eftersom de flesta R-funktioner kan automatiskt hantera saknande värden med <code>NA</code>-värdet.</li>
<li><code>col_select</code>: Vilka kolumner/variabler ska hämtas in? Utan detta argument läses alla kolumner in.</li>
<li><code>skip</code>: Hur många rader vill du skippa före du börjar läsa in data? Standardvärdet är noll, alltså att funktionen börjar från första dataraden.</li>
<li><code>n_max</code>: Största mängden rader som funktionen läser in.</li>
</ul>
<p>För skrivning av SPSS-data, använd funktionen <code>write_sav(data, path)</code>. Du kan ytterligare ge kompressionsfunktionen som argument, om du vet vad en sådan är och kan använda dem, samt tidszonsdefinitioner.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>readr::write_sav(x, path, ...)</code>: Skriver in data <code>x</code> till en <code>.sav</code>-fil med namnet och adressen <code>path</code>. För övriga inställningar, se hjälpfunktionen <code>?write_sav</code>.</p>
</div></div></section>
<section id="csv" class="level3 page-columns page-full" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="csv"><span class="header-section-number">9.2.2</span> CSV</h3>
<p>Dataformatet vi föredrar är kommaseparerade värden, eller <code>csv</code> (eng. <em>comma-separated values</em>). Detta är ett maskin- och människoläsbart format, där varje datarad är en… rad och värden för raderna listas upp separerade med kommatering - därav namnet. Ungefär så här ser en CSV-fil ut:</p>
<pre><code>1,1,1,1,5,2
1,1,1,2,3,7
0,0,2,2,3,2
1,1,,2,6,3
,,,,,
0,0,0,0,0,0</code></pre>
<p>För att förenkla läsningen av CSV-filer kan du öppna dem i ett kalkylbladprogram så som Excel eller Calc, och se varje värde uppställt i separata celler. Det är dock bra att förstå, att under huven är alla värden bara listade på ovan sätt, lite som en väldigt stor textfil.</p>
<p>Tanken bakom CSV är att formatet ska vara ett öppet, lätt användbart och enkelt strukturerat datasystem. Det är därför lite synd, att det finns <em>olika former</em> av CSV - och du måste bara veta vilken form du har.</p>
<p>Format 1 använder komma som separator (därav namnet CSV) och punkt som decimalskiljetecken: <code>1.5,2.7</code> är två värden, det andra större än det första. Format 2 använder semikolon som separator och komma som decimalskiljetecken: <code>1,5;2,7</code> för samma värde i format 2. Det andra används bl.a. i Norden, eftersom vi tenderar att skriva decimaltal med komma som skiljetecken.</p>
<div class="page-columns page-full"><p>Du kan läsa in CSV-filer med två funktioner från Tidyverse-paketet <code>readr</code>: <code>read_csv(path)</code> och <code>read_csv2(path)</code>. Bägge tar som obligatoriska argument filadressen och returnerar en tibble av de avlästa data. Den första använder kommaseparator, den andra semikolonseparator. Glömmer du vilken är vilken kan du alltid kolla upp <code>?read_csv</code><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p><div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;Märk, att det finns liknande funktioner i paketet <code>foreign</code> om du har det aktiverat. Var noggrann med vad du skriver och hur!</p></li></div></div>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>readr::read_csv(path)</code>: Läser in CSV-data från filen <code>path</code>. Använder kommaseparator och punktdecimal. Returnerar en tibble. <code>readr::read_csv2(path)</code>: Läser in CSV-data från filen <code>path</code>. Använder semikolonseparator och kommadecimal. Returnerar en tibble.</p>
</div></div><p>För att skriva filer använder du motsvarande funktioner <code>write_csv(data, path)</code> (kommaseparation) och <code>write_csv2(data,path)</code> (semikolonseparation) från <code>readr</code>. Första argumentet ger data du vill skriva till en fil, andra argumentet namnet på filen. Filen sparas i din arbetsfilmiljö om du inte specificerar en noggrannare filadress.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p><code>readr::write_csv(x, path)</code>: Skriver objektet <code>x</code> till <code>csv</code>-filen vid namnet och adressen <code>path</code>. Använder kommaseparation och punktdecimal. <code>readr::write_csv2(x, path)</code>: Skriver objektet <code>x</code> till <code>csv</code>-filen vid namnet och adressen <code>path</code>. Använder semikolonseparation och kommadecimal.</p>
</div></div></section>
<section id="andra-format" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="andra-format"><span class="header-section-number">9.2.3</span> Andra format</h3>
<p>Om du får data i andra format kan du först skrika inombords - varför måste det vara så svårt?! - och sedan lugna dig själv med tilltron i R-samhörigheten. Högst troligen finns det en funktion som kan läsa in de mystiska data du har fått, men du måste lite rota. Paketen <code>readr</code>, <code>foreign</code> och <code>haven</code> innehåller många olika läs- och skrivfunktioner. Börja med dem, och om du inte hittar en passande funktion, gå sedan till Google för hjälp. Om inget hjälper, säg åt dataägaren att de tar sig i kragen och levererar ett dataformat som vanliga dödliga kan avläsa.</p>
</section>
<section id="övning-läs-in-barometerdata-till-r" class="level3" data-number="9.2.4">
<h3 data-number="9.2.4" class="anchored" data-anchor-id="övning-läs-in-barometerdata-till-r"><span class="header-section-number">9.2.4</span> Övning: Läs in barometerdata till R</h3>
<p>Nu övar vi datainläsning! Vi hämtar in data från Finlandssvenska barometern 2008 och sparar det som ett tibble-objekt med namnet <code>data</code>. Jag gör koden aningen mer explicit än vad som behövs, för pedagogiska syften.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr) <span class="co"># Aktivera readr. Om paketet är aktivt gör denna rad ingenting.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>path <span class="ot">&lt;-</span> <span class="st">"FSD3200/Study/Data/daF3200.csv"</span> <span class="co"># Byt detta till adressen där du har datafilen.</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv2</span>(path)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ Using "','" as decimal and "'.'" as grouping mark. Use `read_delim()` for more control.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 819 Columns: 116
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr   (1): fsd_li
dbl (115): fsd_no, fsd_vr, fsd_id, q1a_lk, q2_lk, q3, q4, q5, q6, q7, q8, q9...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Nu borde våra data finnas inladdade i objektet <code>data</code>! Vi kan granska detta genom att kalla <code>data</code>, vilket borde ge en förkortad version av tibbleobjektet:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 819 × 116
   fsd_no fsd_vr fsd_id fsd_li  q1a_lk q2_lk    q3    q4    q5    q6    q7    q8
    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1   3200      1      1 (A) öp…      2     6     1     7     4     3     2     0
 2   3200      1      2 (A) öp…      2     5     1     6     4     3     2    NA
 3   3200      1      3 (A) öp…      2     6     1     4     4     1     1    NA
 4   3200      1      4 (A) öp…     NA     6     2     3     4     3     2    NA
 5   3200      1      5 (A) öp…      4     6     1     3     4     3     2    NA
 6   3200      1      6 (A) öp…      9     5     2     7     4     3     2    NA
 7   3200      1      7 (A) öp…      2     6     1     3     4     1     1    NA
 8   3200      1      8 (A) öp…      2     6     1     3     4     3     2    NA
 9   3200      1      9 (A) öp…      9     6     2     7     4     1     1    NA
10   3200      1     10 (A) öp…      2     2     1     2     1     3     2    NA
# … with 809 more rows, and 104 more variables: q9_1 &lt;dbl&gt;, q9_2 &lt;dbl&gt;,
#   q9_3 &lt;dbl&gt;, q9_4 &lt;dbl&gt;, q9_5 &lt;dbl&gt;, q9_6 &lt;dbl&gt;, q10 &lt;dbl&gt;, q11_1 &lt;dbl&gt;,
#   q11_2 &lt;dbl&gt;, q11_3 &lt;dbl&gt;, q11_4 &lt;dbl&gt;, q11_5 &lt;dbl&gt;, q12_1 &lt;dbl&gt;,
#   q12_2 &lt;dbl&gt;, q12_2b &lt;dbl&gt;, q12_2c &lt;dbl&gt;, q12_3 &lt;dbl&gt;, q12_4 &lt;dbl&gt;,
#   q12_5 &lt;dbl&gt;, q12_6 &lt;dbl&gt;, q12_7 &lt;dbl&gt;, q12_8 &lt;dbl&gt;, q12_9 &lt;dbl&gt;,
#   q12_10 &lt;dbl&gt;, q12_11 &lt;dbl&gt;, q12_12 &lt;dbl&gt;, q13_1 &lt;dbl&gt;, q13_2 &lt;dbl&gt;,
#   q14_1 &lt;dbl&gt;, q14_2 &lt;dbl&gt;, q15_1 &lt;dbl&gt;, q15_2 &lt;dbl&gt;, q15_3 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>Allt fungerade bra! Från förhandsgranskningen av tibbleobjektet ser vi att vi har 819 rader data (respondenter) och 116 kolumner (statistiska variabler). Inläsningsfunktionen producerar även en hel del debuggningstext, som kan vara nyttigt om du märker fel i inläsningen. För att försäkra oss att allt gick korrekt kan vi öppna den ursprungliga <code>csv</code>-filen i ett kalkylbladprogram och jämföra visuellt med vårt inlästa objekt. Gör du detta, så märker du att saknande värden (tomma celler i CSV-filen) har konverterats till <code>NA</code>-värden i R - något vi oftast vill att ska ske, som tur.</p>
<p>Om du jobbar i RStudio kan du även öppna <code>data</code>-objektet från Environment-tabben i övre högra hörnet. I denna vy kan du visuellt bearbeta materialet, t.ex. lägga på olika värdefilter eller t.o.m. ändra enskilda datapunkters värden. Vi strävar däremot att jobba i kod så långt som möjligt för pedagogiska syften - det är bäst att du först lär dig kod, sedan lättare verktyg, så att du kan lösa mer komplexa problem i datahanteringen om/när de uppstår. Sträva alltså till att göra saker i kod först, och ta de visuella verktygen i bruk senare.</p>
<p>Däremot har vi ett problem: vi vet ju inte vad dessa variabler betyder! I nästa kapitel hanterar vi några grundläggande datamanipuleringsmetoder i R, och putsar upp vårt dataset till något mer brukbart.</p>


</section>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./grundläggande-kunskaper-i-programmering.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Grundläggande kunskaper i R-programmering</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./grafik.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Grafik</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>